// Test generated by RoostGPT for test java-mvn using AI Type Open AI and AI Model gpt-3.5-turbo

import com.wangzaiplus.test.common.Constant;
import com.wangzaiplus.test.service.MsgLogService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.core.Binding;
import org.springframework.amqp.core.BindingBuilder;
import org.springframework.amqp.core.DirectExchange;
import org.springframework.amqp.core.Queue;
import org.springframework.amqp.rabbit.connection.CachingConnectionFactory;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.amqp.support.converter.Jackson2JsonMessageConverter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Slf4j
@Configuration
public class RabbitConfig {

    @Autowired
    private MsgLogService msgLogService;

    @Bean
    public Jackson2JsonMessageConverter converter() {
        return new Jackson2JsonMessageConverter();
    }

    // TODO: Write test cases to ensure the method is working correctly

    public void testConverterReturnsNonNullObject() {
        Jackson2JsonMessageConverter converter = converter();
        assert converter != null;
    }

    public void testConverterReturnsJackson2JsonMessageConverterInstance() {
        Jackson2JsonMessageConverter converter = converter();
        assert converter instanceof Jackson2JsonMessageConverter;
    }
}
