// Test generated by RoostGPT for test springboot using AI Type Open AI and AI Model gpt-4

package com.wangzaiplus.test.config;

import com.wangzaiplus.test.common.Constant;
import com.wangzaiplus.test.service.MsgLogService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.core.Queue;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.mockito.Mockito;

@SpringBootTest
public class RabbitConfig_logUserQueue_885f8456e3_Test {
    
    @Autowired
    private RabbitConfig rabbitConfig;

    @MockBean
    private MsgLogService msgLogService;

    @Test
    public void testLogUserQueue_Success() {
        String queueName = "LOGIN_LOG_QUEUE_NAME";
        Mockito.when(msgLogService.getQueueName()).thenReturn(queueName);
        Queue queue = rabbitConfig.logUserQueue();
        assertNotNull(queue);
        assertEquals(queueName, queue.getName());
        assertTrue(queue.isDurable());
    }

    @Test
    public void testLogUserQueue_Failure() {
        String queueName = "WRONG_QUEUE_NAME";
        Mockito.when(msgLogService.getQueueName()).thenReturn(queueName);
        Queue queue = rabbitConfig.logUserQueue();
        assertNotNull(queue);
        assertNotEquals(queueName, queue.getName());
    }
}
