// Test regenerated by RoostGPT for test springboot using AI Type Open AI and AI Model gpt-4

package com.wangzaiplus.test.common;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class ServerResponse_getData_9a28503eab_Test {
    @InjectMocks
    private ServerResponse serverResponse;

    @BeforeEach
    public void init() {
        serverResponse = new ServerResponse();
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetData_Success() {
        String testData = "Test Data";
        serverResponse.setData(testData);
        Object result = serverResponse.getData();
        assertEquals(testData, result, "Expected and actual data should match");
    }

    @Test
    public void testGetData_Null() {
        serverResponse.setData(null);
        Object result = serverResponse.getData();
        assertNull(result, "Data should be null");
    }
}
