// Test generated by RoostGPT for test springboot using AI Type Open AI and AI Model gpt-4

package com.wangzaiplus.test.common;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class ServerResponse_error_67c4212269_Test {

    @MockBean
    private ServerResponse serverResponse;

    @BeforeEach
    public void setUp() {
        Mockito.when(serverResponse.error(Mockito.anyString(), Mockito.anyObject()))
            .thenAnswer(i -> new ServerResponse(ResponseCode.ERROR.getCode(), i.getArgument(0), i.getArgument(1)));
    }

    @Test
    public void testErrorMethodWithValidInput() {
        String errorMessage = "An error occurred";
        String data = "Data";
        ServerResponse response = serverResponse.error(errorMessage, data);
        assertEquals(ResponseCode.ERROR.getCode(), response.getCode());
        assertEquals(errorMessage, response.getMsg());
        assertEquals(data, response.getData());
    }

    @Test
    public void testErrorMethodWithNullInput() {
        ServerResponse response = serverResponse.error(null, null);
        assertEquals(ResponseCode.ERROR.getCode(), response.getCode());
        assertEquals(null, response.getMsg());
        assertEquals(null, response.getData());
    }
}
